export const oneDayMilliseconds = 24 * 60 * 60 * 1000;

export const emptyPolls: Poll[] = [];

export const samplePolls: Poll[] = [
  {
    id: 0,
    creator: "0xADDRESS1",
    title: "Favorite Color Survey",
    question: "What is your favorite color?",
    optionTexts: ["Red", "Green", "Blue"],
    optionVotes: [10, 15, 20],
    voterCount: 45,
    deadline: 1700000000, // Example future timestamp
    createdAt: 1690000000,
    hasAlreadyVoted: false,
  },
  {
    id: 1,
    creator: "0xADDRESS2",
    title: "Sports Watch Preferences",
    question: "Which sports do you enjoy watching?",
    optionTexts: ["Soccer", "Basketball", "Tennis", "Golf"],
    optionVotes: [5, 10, 15, 20],
    voterCount: 25,
    deadline: 1700001000,
    createdAt: 1690001000,
    hasAlreadyVoted: false,
  },
  {
    id: 2,
    creator: "0xADDRESS3",
    title: "Pet Preference Poll",
    question: "Do you prefer dogs or cats?",
    optionTexts: ["Dogs", "Cats"],
    optionVotes: [30, 25],
    voterCount: 55,
    deadline: 1700002000,
    createdAt: 1690002000,
    hasAlreadyVoted: false,
  },
  {
    id: 3,
    creator: "0xADDRESS1",
    title: "Programming Language Favorites",
    question: "What is your favorite programming language?",
    optionTexts: ["JavaScript", "Python", "Java", "C++"],
    optionVotes: [25, 20, 15, 10],
    voterCount: 70,
    deadline: 1700003000,
    createdAt: 1690003000,
    hasAlreadyVoted: false,
  },
  {
    id: 4,
    creator: "0xADDRESS4",
    title: "Music Genre Preferences",
    question: "Which genres of music do you like?",
    optionTexts: ["Rock", "Pop", "Jazz", "Classical"],
    optionVotes: [10, 15, 20, 5],
    voterCount: 50,
    deadline: 1700004000,
    createdAt: 1690004000,
    hasAlreadyVoted: false,
  },
  {
    id: 5,
    creator: "0xADDRESS5",
    title: "Exercise Frequency Survey",
    question: "How often do you exercise?",
    optionTexts: ["Daily", "Weekly", "Monthly", "Rarely"],
    optionVotes: [20, 15, 5, 10],
    voterCount: 50,
    deadline: 1700005000,
    createdAt: 1690005000,
    hasAlreadyVoted: false,
  },
  {
    id: 6,
    creator: "0xADDRESS2",
    title: "Transportation Preferences",
    question: "What is your preferred mode of transportation?",
    optionTexts: ["Car", "Bicycle", "Public Transport", "Walking"],
    optionVotes: [12, 8, 10, 5],
    voterCount: 35,
    deadline: 1700006000,
    createdAt: 1690006000,
    hasAlreadyVoted: false,
  },
  {
    id: 7,
    creator: "0xADDRESS3",
    title: "Streaming Service Preferences",
    question: "Which streaming services do you use?",
    optionTexts: ["Netflix", "HBO Max", "Disney+", "Hulu"],
    optionVotes: [15, 10, 12, 8],
    voterCount: 20,
    deadline: 1700007000,
    createdAt: 1690007000,
    hasAlreadyVoted: false,
  },
  {
    id: 8,
    creator: "0xADDRESS4",
    title: "Favorite Season Poll",
    question: "What is your favorite season?",
    optionTexts: ["Spring", "Summer", "Fall", "Winter"],
    optionVotes: [10, 15, 20, 5],
    voterCount: 50,
    deadline: 1700008000,
    createdAt: 1690008000,
    hasAlreadyVoted: false,
  },
  {
    id: 9,
    creator: "0xADDRESS5",
    title: "Social Media Usage Survey",
    question: "Which social media platforms do you use regularly?",
    optionTexts: ["Facebook", "Twitter", "Instagram", "LinkedIn"],
    optionVotes: [8, 12, 15, 5],
    voterCount: 25,
    deadline: 1700009000,
    createdAt: 1690009000,
    hasAlreadyVoted: false,
  },
];

export const personalPolls: Poll[] = [
  {
    id: 10,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 11,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 12,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 13,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 14,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 15,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 16,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 17,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 18,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
  {
    id: 19,
    creator: "0xADDRESS6",
    title: "Cuisine Preference Poll",
    question: "What is your favorite type of cuisine?",
    optionTexts: ["Italian", "Chinese", "Mexican", "Indian"],
    optionVotes: [15, 20, 10, 25],
    voterCount: 30,
    deadline: 1700010000,
    createdAt: 1690010000,
    hasAlreadyVoted: false,
  },
];
